global using System.Net.Mail;
global using System.Reflection;
global using Ardalis.GuardClauses;
global using Ardalis.SharedKernel;
global using Ardalis.Specification.EntityFrameworkCore;
global using ShoppingListEntity = ShoppingList.List.Core.ShoppingListAggregate.ShoppingList;
global using ListItemEntity = ShoppingList.List.Core.ShoppingListAggregate.ListItem;
global using CategoryEntity = ShoppingList.List.Core.ShoppingListAggregate.Category;
global using ShareLinkEntity = ShoppingList.List.Core.ShoppingListAggregate.ShareLink;
global using ListChangeEntity = ShoppingList.List.Core.ShoppingListAggregate.ListChange;
global using BatchOperationEntity = ShoppingList.List.Core.ShoppingListAggregate.BatchOperation;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using MimeKit;
